//
//  PostDetailsInteractorTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostDetailsInteractorTests: XCTestCase {
    // MARK: Subject under test
    var sut: PostDetailsInteractor!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        setupPostDetailsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    func setupPostDetailsInteractor() {
        sut = PostDetailsInteractor()
    }
    
    // MARK: Test doubles
    class PostDetailsPresentationLogicSpy: PostDetailsPresentationLogic {
        var presentPostCalled = false

        func presentPost(response: PostDetails.GetPost.Response) {
            presentPostCalled = true
        }
    }
    
    // MARK: Tests
    func interactorShouldAskPresenterToPresentPost() {
        // Given
        let presentationLogicSpy = PostDetailsPresentationLogicSpy()
        sut.presenter = presentationLogicSpy

        let request = PostDetails.GetPost.Request()

        // When
        sut.getPost(request: request)

        // Then
        XCTAssertTrue(presentationLogicSpy.presentPostCalled, "getPost() should call present post on presenter")
    }
}
