//
//  PostDetailsViewControllerTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostDetailsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    var sut: PostDetailsViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupPostDetailsViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    func setupPostDetailsViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "PostDetailsViewController") as? PostDetailsViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    class PostDetailsBusinessLogicSpy: PostDetailsBusinessLogic {
        var getPostCalled = false

        func getPost(request: PostDetails.GetPost.Request) {
            getPostCalled = true
        }
    }
    
    // MARK: Tests
    func testShouldGetPostWhenViewWillAppear() {
        // Given
        let spy = PostDetailsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.viewWillAppear(false)
        
        // Then
        XCTAssertTrue(spy.getPostCalled, "viewDidLoad() should ask the interactor to get post")
    }
    
    func testDisplayPost() {
        // Given
        let body = "post body"
        let displayable = PostDetails.GetPost.ViewModel.DisplayedPost(body: body)
        let viewModel = PostDetails.GetPost.ViewModel(displayedPost: displayable)

        let spy = PostDetailsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        sut.displayPost(viewModel: viewModel)
        
        // Then
        XCTAssertEqual(sut.bodyTextView.text, body, "displayPost(viewModel:) should update the body text view")
    }
}
