//
//  PostDetailsInteractorTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostDetailsInteractorTests: XCTestCase {
    // MARK: Subject under test
    var sut: PostDetailsInteractor!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        setupPostDetailsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    func setupPostDetailsInteractor() {
        sut = PostDetailsInteractor()
    }
    
    // MARK: Test doubles
    class PostDetailsPresentationLogicSpy: PostDetailsPresentationLogic {
        var presentPostCalled = false
        var presentToggleFavoriteCalled = false
        var presentUpdatePostsListCalled = false

        func presentPost(response: PostDetails.GetPost.Response) {
            presentPostCalled = true
        }

        func presentToggleFavorite(response: PostDetails.ToggleFavorite.Response) {
            presentToggleFavoriteCalled = true
        }

        func presentUpdatePostsList(response: PostDetails.UpdatePostsList.Response) {
            presentUpdatePostsListCalled = true
        }
    }

    class PostDetailsWorkerSpy: PostDetailsWorker {
        var fetchUserCalled = false

        override func fetchUser(id: Int, completionHandler: @escaping ((User) -> ())) {
            fetchUserCalled = true

            let user = User(name: "", email: "", phone: "", website: "")
            completionHandler(user)
        }
    }
    
    // MARK: Tests
    func testInteractorShouldAskPresenterToPresentPost() {
        // Given
        let presentationLogicSpy = PostDetailsPresentationLogicSpy()
        sut.presenter = presentationLogicSpy

        let workerSpy = PostDetailsWorkerSpy()
        sut.worker = workerSpy

        let post = Post(userId: 1, id: 1, title: "", body: "")
        sut.post = post

        let request = PostDetails.GetPost.Request()

        // When
        sut.getPost(request: request)

        // Then
        XCTAssertTrue(presentationLogicSpy.presentPostCalled, "getPost() should call present post on presenter")
        XCTAssertTrue(workerSpy.fetchUserCalled, "getPost() should call worker to fetch user info")
    }
}
