//
//  PostDetailsWorkerTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostDetailsWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostDetailsWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPostDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostDetailsWorker() {
        sut = PostDetailsWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
