//
//  PostDetailsPresenter.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostDetailsPresentationLogic {
    func presentSomething(response: PostDetails.Something.Response)
}

class PostDetailsPresenter: PostDetailsPresentationLogic {
    weak var viewController: PostDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: PostDetails.Something.Response) {
        let viewModel = PostDetails.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
