//
//  PostDetailsWorker.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/10/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class PostDetailsWorker {
    private let userUrl = "https://jsonplaceholder.typicode.com/users/"

    func fetchUser(id: Int, completionHandler: @escaping ((User) -> ())) {
        Alamofire.request("\(userUrl)\(id)").responseJSON { (dataResponse) in
            if let data = dataResponse.data {
                let decoder = JSONDecoder()

                do {
                    let user = try decoder.decode(User.self, from: data)
                    completionHandler(user)
                } catch {
                    print("error decoding user")
                    print(error)
                }
            }
        }
    }
}
