//
//  PostsListInteractorTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostsListInteractorTests: XCTestCase {
    // MARK: Subject under test
    var sut: PostsListInteractor!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        setupPostsListInteractor()
    }
    
    // MARK: Test setup
    func setupPostsListInteractor() {
        sut = PostsListInteractor()
    }
    
    // MARK: Test doubles
    class PostsListPresentationLogicSpy: PostsListPresentationLogic {
        var presentPostsCalled = false

        func presentPosts(response: PostsList.FetchPosts.Response) {
            presentPostsCalled = true
        }

        func presentPosts(response: PostsList.DeletePosts.Response) {
            presentPostsCalled = true
        }
    }

    class PostsListWorkerSpy: PostsListWorker {
        var fetchPostsCalled = false
        var deletePostCalled = false
        var deleteAllPostsCalled = false

        override func fetchPosts(completionHandler: @escaping (([PostsList.Post]) -> ())) {
            fetchPostsCalled = true
            completionHandler([])
        }

        override func deletePost(id: Int) -> [PostsList.Post] {
            deletePostCalled = true
            return []
        }

        override func deleteAllPosts() {
            deleteAllPostsCalled = true
        }
        
    }
    
    // MARK: Tests
    func testFetchShouldAskPostsListWorkerToFetchPostsAndPresenterToFormatThem() {
        // Given
        let postsListPresentationLogicSpy = PostsListPresentationLogicSpy()
        let postsListWorkerSpy = PostsListWorkerSpy()

        sut.worker = postsListWorkerSpy
        sut.presenter = postsListPresentationLogicSpy

        // When
        let request = PostsList.FetchPosts.Request()
        sut.fetch(request: request)

        // Then
        XCTAssertTrue(postsListWorkerSpy.fetchPostsCalled, "fetch() should ask worker to fetch posts")
        XCTAssertTrue(postsListPresentationLogicSpy.presentPostsCalled, "fetch() should ask presenter to format posts")
    }

    func testDeleteShouldAskPostListWorkerToDeletePostAndPresenterToFormatResponse() {
        //Given
        let postsListPresentationLogicSpy = PostsListPresentationLogicSpy()
        let postsListWorkerSpy = PostsListWorkerSpy()

        sut.worker = postsListWorkerSpy
        sut.presenter = postsListPresentationLogicSpy

        // When
        let request = PostsList.DeletePosts.Request(id: 0)
        sut.delete(request: request)

        // Then
        XCTAssertTrue(postsListWorkerSpy.deletePostCalled, "delete() should ask worker to delete posts")
        XCTAssertTrue(postsListPresentationLogicSpy.presentPostsCalled, "delete() should ask presenter to format response")
    }

    func testDeleteShouldAskPostsListWorkerToDeleteAllPostsAndPresenterToFormatResponse() {
        //Given
        let postsListPresentationLogicSpy = PostsListPresentationLogicSpy()
        let postsListWorkerSpy = PostsListWorkerSpy()

        sut.worker = postsListWorkerSpy
        sut.presenter = postsListPresentationLogicSpy

        // When
        let request = PostsList.DeletePosts.Request()
        sut.deleteAll(request: request)

        // Then
        XCTAssertTrue(postsListWorkerSpy.deleteAllPostsCalled, "delete() should ask worker to delete posts")
        XCTAssertTrue(postsListPresentationLogicSpy.presentPostsCalled, "delete() should ask presenter to format response")
    }
}
