//
//  PostsListInteractorTests.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Posts
import XCTest

class PostsListInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: PostsListInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupPostsListInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupPostsListInteractor() {
        sut = PostsListInteractor()
    }
    
    // MARK: Test doubles
    
    class PostsListPresentationLogicSpy: PostsListPresentationLogic {
        var presentSomethingCalled = false
        
        func presentSomething(response: PostsList.Something.Response) {
            presentSomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = PostsListPresentationLogicSpy()
        sut.presenter = spy
        let request = PostsList.Something.Request()
        
        // When
        sut.doSomething(request: request)
        
        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
