//
//  PostsListModels.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostsList {

 
    // MARK: Use cases
    enum FetchPosts {
        struct Request {
        }

        struct Response {
            let posts: [Post]
        }

        struct ViewModel {
            var posts: [Post]
        }
    }

    enum DeletePosts {
        struct Request {
            var post: Post?
        }

        struct Response {
            let posts: [Post]
        }

        struct ViewModel {
            var posts: [Post]
        }
    }

    enum FilterPosts {
        enum Filter {
            case all
            case favorites
        }

        struct Request {
            var filter: Filter
        }

        struct Response {
            let posts: [Post]
        }

        struct ViewModel {
            let posts: [Post]
        }
    }
}
