//
//  PostsListModels.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostsList {

    struct Post {
        let userId: Int
        let id: Int
        let title: String
        let body: String
        var isFavorite: Bool = false
        var isUnread: Bool = false
    }

    // MARK: Use cases
    enum FetchPosts {
        struct Request {
            var index: Int = -1
        }

        struct Response {
            let posts: [Post]
        }

        struct ViewModel {
            var posts: [Post]
        }
    }

    enum DeletePosts {
        struct Request {
            var index: Int = -1
        }

        struct Response {
            var index: Int = -1
            let posts: [Post]
        }

        struct ViewModel {
            var index: Int = -1
            var posts: [Post]
        }
    }
}

extension PostsList.Post: Codable {

    enum CodingKeys: String, CodingKey {
        case userId, id, title, body, isFavorite, isUnread
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        userId = try container.decode(Int.self, forKey: .userId)
        id = try container.decode(Int.self, forKey: .id)
        title = try container.decode(String.self, forKey: .title)
        body = try container.decode(String.self, forKey: .body)
        isFavorite = false
        isUnread = false
    }
}
