//
//  PostsListRouter.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PostsListRoutingLogic {
    func routeToPostDetails(segue: UIStoryboardSegue?)
}

protocol PostsListDataPassing {
    var dataStore: PostsListDataStore? { get }
}

class PostsListRouter: NSObject, PostsListRoutingLogic, PostsListDataPassing {
    weak var viewController: PostsListViewController?
    var dataStore: PostsListDataStore?
    
    // MARK: Routing
    func routeToPostDetails(segue: UIStoryboardSegue?) {
        if let dataStore = dataStore,
            let destinationVC = segue?.destination as? PostDetailsViewController,
            var destinationDS = destinationVC.router?.dataStore {

            passDataToPostDetails(source: dataStore, destination: &destinationDS)
        }
    }
    
    // MARK: Passing data
    func passDataToPostDetails(source: PostsListDataStore, destination: inout PostDetailsDataStore) {
        if let selectedPost = viewController?.postsTableView.indexPathForSelectedRow?.row {
            destination.post = source.getPostFor(index: selectedPost)
        }
    }
}
