//
//  PostsListWorker.swift
//  Posts
//
//  Created by Santiago Pelaez Rua on 10/9/19.
//  Copyright (c) 2019 Santiago Pelaez Rua. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class PostsListWorker {
    private var postsUrl = "https://jsonplaceholder.typicode.com/posts"
    private var posts: [PostsList.Post] = []

    /**
     fetch posts from network or cache when available
     - returns: An array of posts
     */
    func fetchPosts(completionHandler: @escaping (([PostsList.Post]) -> ())){
        Alamofire.request(postsUrl).responseJSON { dataResponse in
            if let data = dataResponse.data {
                let decoder = JSONDecoder()

                do {
                    self.posts = try decoder.decode([PostsList.Post].self, from: data)
                    completionHandler(self.posts)
                } catch {
                    print("error trying to decode response")
                    print(error.localizedDescription)
                }
            }
        }
    }

    /**
     delete a single post
     - parameter index: Index for the post to be deleted as Int
     - returns: An array of posts without the deleted post
     */
    func deletePost(at index: Int) -> [PostsList.Post] {
        posts.remove(at: index)

        return posts
    }

    /**
     deletes all posts
     */
    func deleteAllPosts() {
        posts = []
    }
}
